[tool.poetry]
name = "guacapy"
version = "0.11.1"
description = "REST API client for Apache Guacamole"
authors = ["Philipp Schmitt <philipp@schmitt.co>"]
license = "GPL3"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.6"
simplejson = "^3.17.2"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80
